import assert from "node:assert/strict";
import { describe, it } from "vitest";
import {
  createGuestReservationTrackingService,
  createReservationService,
  createPaymentSessionService,
  InMemoryWorkspaceRepository,
  ReservationMemoryRepository,
} from "@deskatlas/domain";

describe("MF-92: Customer Track Reservation Status CTA & Routing", () => {
  it("resolves reservation tracking by reference code and email without 404", async () => {
    const reservationRepo = new ReservationMemoryRepository();
    const workspaceRepo = new InMemoryWorkspaceRepository();
    const paymentSessionService = createPaymentSessionService(reservationRepo);
    const reservationService = createReservationService(
      reservationRepo,
      workspaceRepo,
      reservationRepo,
      paymentSessionService
    );
    const trackingService = createGuestReservationTrackingService(reservationRepo);

    const floor = await workspaceRepo.createFloor({ name: "1st Floor" });
    const template = await workspaceRepo.createTemplate({
      name: "Private Pod",
      capacity: 1,
      rateAmount: 150,
      pricingUnit: "HOURLY",
      defaultShape: "rectangle",
      defaultColor: "#1e293b",
      isActive: true,
    });
    const instance = await workspaceRepo.createInstance({
      templateId: template.id,
      floorId: floor.id,
      instanceCode: "POD-01",
      displayName: "Pod 1",
    });

    const reservation = await reservationService.createReservation(
      {
        source: "WEB",
        customerFirstName: "Juan",
        customerLastName: "Dela Cruz",
        customerEmail: "juan.delacruz@example.com",
        candidates: [
          {
            rank: 0,
            workspaceInstanceId: instance.id,
            startAt: "2026-09-20T09:00:00.000Z",
            endAt: "2026-09-20T11:00:00.000Z",
          },
        ],
      },
      { paymentLinkBaseUrl: "https://deskatlas.test/pay" }
    );

    // Test 1: URL query pattern generated by the CTA button in ReservationPage.tsx
    const refCode = reservation.referenceCode;
    const email = "juan.delacruz@example.com";
    const generatedCtaUrl = `/track?code=${encodeURIComponent(refCode)}&email=${encodeURIComponent(email)}`;
    assert.equal(
      generatedCtaUrl,
      `/track?code=${encodeURIComponent(refCode)}&email=juan.delacruz%40example.com`
    );

    // Parse URL params as TrackingPage component does
    const parsedParams = new URLSearchParams(generatedCtaUrl.replace("/track?", ""));
    const codeFromParams = parsedParams.get("code");
    const emailFromParams = parsedParams.get("email");

    assert.equal(codeFromParams, refCode);
    assert.equal(emailFromParams, email);

    // Verify service resolves successfully with query params
    const resultFromQuery = await trackingService.getReservationTracking({
      referenceCode: codeFromParams!,
      customerEmail: emailFromParams!,
    });
    assert.equal(resultFromQuery.referenceCode, refCode);
    assert.equal(resultFromQuery.status, "PENDING_PAYMENT");
    assert.equal(resultFromQuery.amountDue, 300);

    // Test 2: Dynamic path parameter pattern /track/[referenceCode]
    const dynamicPath = `/track/${refCode}`;
    const extractedPathCode = decodeURIComponent(dynamicPath.replace("/track/", ""));
    assert.equal(extractedPathCode, refCode);

    // Verify service resolves successfully with path code alone (guest tracking allows reference code lookup)
    const resultFromPath = await trackingService.getReservationTracking({
      referenceCode: extractedPathCode,
    });
    assert.equal(resultFromPath.referenceCode, refCode);
    assert.equal(resultFromPath.status, "PENDING_PAYMENT");
  });

  it("handles whitespace and case variations consistently", async () => {
    const reservationRepo = new ReservationMemoryRepository();
    const workspaceRepo = new InMemoryWorkspaceRepository();
    const paymentSessionService = createPaymentSessionService(reservationRepo);
    const reservationService = createReservationService(
      reservationRepo,
      workspaceRepo,
      reservationRepo,
      paymentSessionService
    );
    const trackingService = createGuestReservationTrackingService(reservationRepo);

    const floor = await workspaceRepo.createFloor({ name: "2nd Floor" });
    const template = await workspaceRepo.createTemplate({
      name: "Desk",
      capacity: 1,
      rateAmount: 100,
      pricingUnit: "HOURLY",
      defaultShape: "rectangle",
      defaultColor: "#1e293b",
      isActive: true,
    });
    const instance = await workspaceRepo.createInstance({
      templateId: template.id,
      floorId: floor.id,
      instanceCode: "DK-01",
      displayName: "Desk 01",
    });

    const reservation = await reservationService.createReservation(
      {
        source: "WEB",
        customerFirstName: "Maria",
        customerLastName: "Clara",
        customerEmail: "maria.clara@example.com",
        candidates: [
          {
            rank: 0,
            workspaceInstanceId: instance.id,
            startAt: "2026-09-20T13:00:00.000Z",
            endAt: "2026-09-20T15:00:00.000Z",
          },
        ],
      },
      { paymentLinkBaseUrl: "https://deskatlas.test/pay" }
    );

    // Query with mixed case and leading/trailing whitespace
    const trackingResult = await trackingService.getReservationTracking({
      referenceCode: `  ${reservation.referenceCode.toLowerCase()}  `,
      customerEmail: "  MARIA.CLARA@EXAMPLE.COM  ",
    });

    assert.equal(trackingResult.referenceCode, reservation.referenceCode);
    assert.equal(trackingResult.status, "PENDING_PAYMENT");
  });
});
